title: JetUML
description: A desktop application for fast UML diagramming
theme: just-the-docs

url: https://jkcoding7.github.io/laughing-train

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/prmr/JetUML
