title: JetUML
description: A desktop application for fast UML diagramming
theme: just-the-docs

url: https://jkcoding7.github.io/laughing-train
 
aux_links: 
  View on GitHub: https://github.com/prmr/JetUML

aux_links_new_tab: true

defaults:
  -
    nav_enabled: false
